# This workflow sets up the Earth Engine token and runs all tests.

name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .[test]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: token
      run: |
        python ./.github/scripts/make_ee_token.py
      env:
        EE_TOKEN: ${{ secrets.EE_TOKEN }}
    - name: Test with pytest
      run: |
        pytest .
